name: Automated Tagging and Deployment

# Events that trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

# Set permissions to allow pushing tags
permissions:
  contents: write  # Grants write access to the repository's contents (necessary for pushing tags)

jobs:
  create-tag-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set IMAGE_TAG for non-release events (push to main)
      - name: Set IMAGE_TAG for non-release events
        if: github.event_name != 'pull_request' && github.event_name != 'release'
        shell: bash
        run: |
          # Extract branch name from GITHUB_REF and remove refs/heads/
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ -z "$BRANCH_NAME" ]]; then
            BRANCH_NAME="main"
          fi
          # Format the tag as branchname-YYYYMMDD-HHMMSS
          echo "IMAGE_TAG=${BRANCH_NAME//\//-}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Step 3: Set IMAGE_TAG (on pull_request event)
      - name: Set IMAGE_TAG (on pull_request event)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          # Format the tag as branchname-YYYYMMDD-HHMMSS
          echo "IMAGE_TAG=${BRANCH_NAME//\//-}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Step 4: Set IMAGE_TAG (on release event)
      - name: Set IMAGE_TAG (on release event)
        if: github.event_name == 'release'
        shell: bash
        run: |
          # Format the tag as release-tagname-YYYYMMDD-HHMMSS
          echo "IMAGE_TAG=release-${{ github.event.release.tag_name }}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Step 5: Debug IMAGE_TAG
      - name: Debug IMAGE_TAG
        run: echo "IMAGE_TAG is $IMAGE_TAG"

      # Step 6: Create and push the tag using GITHUB_TOKEN
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "Creating tag: $IMAGE_TAG"
          git tag $IMAGE_TAG
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $IMAGE_TAG
