name: Automated Tagging and Deployment

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-tag-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set IMAGE_TAG
        shell: bash
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ -z "$BRANCH_NAME" ]]; then
            BRANCH_NAME="manual"
          fi
          # Format the tag as YYYYMMDD-HHMMSS-branchname
          echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')-${BRANCH_NAME//\//-}" >> $GITHUB_ENV

      - name: Debug IMAGE_TAG
        run: echo "IMAGE_TAG is $IMAGE_TAG"

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "Creating tag: $IMAGE_TAG"
          git tag $IMAGE_TAG
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $IMAGE_TAG